inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.3
  DisplayCopNames: true
  DisplayStyleGuide: true
  Include:
    - Capfile
    - Gemfile
    - '**/Rakefile'
    - '**/config.ru'
    - '**/*.rake'
  Exclude:
    - 'db/schema.rb'
    - 'vendor/**/*'

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 100

Metrics/ParameterLists:
  Max: 6

Rails/NotNullColumn:
  Enabled: false

Style/AlignArray:
  Enabled: false

# Configuration parameters: EnforcedHashRocketStyle, EnforcedColonStyle, EnforcedLastArgumentHashStyle, SupportedLastArgumentHashStyles.
# SupportedLastArgumentHashStyles: always_inspect, always_ignore, ignore_implicit, ignore_explicit
Style/AlignHash:
  Enabled: false

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation
  IndentationWidth: 4

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/Encoding:
  Enabled: true

Style/FirstParameterIndentation:
  IndentationWidth: 4

Style/FormatString:
  EnforcedStyle: percent

Style/IndentArray:
  IndentationWidth: 4

# Configuration parameters: EnforcedStyle, SupportedStyles, IndentationWidth.
# SupportedStyles: special_inside_parentheses, consistent, align_braces
Style/IndentHash:
  IndentationWidth: 4

Style/IndentAssignment:
  IndentationWidth: 4

Style/Lambda:
  EnforcedStyle: literal

Style/MultilineBlockChain:
  Enabled: false

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented
  IndentationWidth: 4

Style/MultilineOperationIndentation:
  EnforcedStyle: indented
  IndentationWidth: 4

Style/PerlBackrefs:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

Style/VariableNumber:
  Enabled: false
