# Offense count: 202
Metrics/AbcSize:
  Max: 228

# Offense count: 1
Metrics/BlockNesting:
  Max: 6

# Offense count: 17
# Configuration parameters: CountComments.
Metrics/ClassLength:
  Max: 384

# Offense count: 36
Metrics/CyclomaticComplexity:
  Max: 27

# Offense count: 1015
# Configuration parameters: AllowHeredoc, AllowURI, URISchemes.
# URISchemes: http, https
Metrics/LineLength:
  Max: 597

# Offense count: 159
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 155

# Offense count: 31
Metrics/PerceivedComplexity:
  Max: 27

# Offense count: 294
Style/Documentation:
  Enabled: false
