# Offense count: 200
Metrics/AbcSize:
  Max: 228

# Offense count: 17
# Configuration parameters: CountComments.
Metrics/ClassLength:
  Max: 382

# Offense count: 35
Metrics/CyclomaticComplexity:
  Max: 27

# Offense count: 1005
# Configuration parameters: AllowHeredoc, AllowURI, URISchemes.
# URISchemes: http, https
Metrics/LineLength:
  Max: 291

# Offense count: 156
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 155

# Offense count: 31
Metrics/PerceivedComplexity:
  Max: 27

# Offense count: 294
Style/Documentation:
  Enabled: false
