# Offense count: 202
Metrics/AbcSize:
  Max: 228

# Offense count: 22
# Configuration parameters: CountComments.
Metrics/BlockLength:
  Max: 167

# Offense count: 20
# Configuration parameters: CountComments.
Metrics/ClassLength:
  Max: 409

# Offense count: 35
Metrics/CyclomaticComplexity:
  Max: 27

# Offense count: 205
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 169

# Offense count: 32
Metrics/PerceivedComplexity:
  Max: 27

# Offense count: 76
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: strict, flexible
Rails/Date:
  Enabled: false

# Offense count: 27
# Cop supports --auto-correct.
# Configuration parameters: Whitelist.
# Whitelist: find_by_sql
Rails/DynamicFindBy:
  Exclude:
    - 'app/models/attendance_history_graph.rb'
    - 'app/models/graduation.rb'
    - 'app/models/member.rb'
    - 'app/models/member_grade_history_graph.rb'
    - 'app/models/nkf_member_comparison.rb'
    - 'app/models/nkf_member_import.rb'
    - 'app/models/user_system.rb'
    - 'db/migrate/20080828192131_add_family_to_martial_art.rb'
    - 'db/migrate/20080828193209_add_martial_arts_members.rb'
    - 'db/migrate/20080828220940_create_groups.rb'
    - 'db/migrate/20111205171636_add_group_id_to_ranks.rb'
    - 'db/migrate/20120604144204_create_member_images.rb'
    - 'test/controllers/info_controller_test.rb'
    - 'test/controllers/user_controller_test.rb'
    - 'test/integration/user_system_test.rb'

# Offense count: 10
# Cop supports --auto-correct.
# Configuration parameters: Include.
# Include: app/models/**/*.rb
Rails/FindBy:
  Exclude:
    - 'app/models/member.rb'
    - 'app/models/news_publisher.rb'
    - 'app/models/nkf_appointments_scraper.rb'
    - 'app/models/nkf_member_import.rb'
    - 'app/models/role.rb'
    - 'app/models/semester.rb'
    - 'app/models/user.rb'

# Offense count: 3
# Configuration parameters: Include.
# Include: app/models/**/*.rb
Rails/HasAndBelongsToMany:
  Exclude:
    - 'app/models/event.rb'
    - 'app/models/group.rb'
    - 'app/models/member.rb'

# Offense count: 291
# Cop supports --auto-correct.
# Configuration parameters: Include.
# Include: spec/**/*, test/**/*
Rails/HttpPositionalArguments:
  Enabled: false

# Offense count: 9
# Configuration parameters: Include.
# Include: app/**/*.rb, config/**/*.rb, db/**/*.rb, lib/**/*.rb
Rails/Output:
  Exclude:
    - 'db/migrate/20080828193209_add_martial_arts_members.rb'
    - 'db/migrate/20080828214833_fix_future_birthdates.rb'
    - 'db/migrate/20080828220940_create_groups.rb'
    - 'db/migrate/20120604144204_create_member_images.rb'
    - 'db/migrate/20150617115412_add_decoration_to_ranks.rb'

# Offense count: 4
Rails/OutputSafety:
  Exclude:
    - 'app/helpers/application_helper.rb'
    - 'app/helpers/user_helper.rb'
    - 'app/mailers/user_message_mailer.rb'
    - 'app/models/event_invitee_message.rb'

# Offense count: 51
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: strict, flexible
Rails/TimeZone:
  Enabled: false

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, IndentationWidth.
# SupportedStyles: with_first_parameter, with_fixed_indentation
Style/AlignParameters:
  Exclude:
    - 'app/models/attendance.rb'

# Offense count: 295
Style/Documentation:
  Enabled: false

# Offense count: 8
# Configuration parameters: MinBodyLength.
Style/GuardClause:
  Exclude:
    - 'app/controllers/application_controller.rb'
    - 'app/mailers/graduation_reminder.rb'
    - 'app/mailers/information_page_notifier.rb'
    - 'app/mailers/nkf_replication_notifier.rb'
    - 'app/mailers/semester_reminder.rb'
    - 'app/models/instruction_reminder.rb'
    - 'app/models/news_publisher.rb'
    - 'app/models/public_record_importer.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: Width.
Style/IndentationWidth:
  Exclude:
    - 'app/models/attendance.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, IndentationWidth.
# SupportedStyles: aligned, indented, indented_relative_to_receiver
Style/MultilineMethodCallIndentation:
  Exclude:
    - 'app/models/attendance.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: ConvertCodeThatCanStartToReturnNil.
Style/SafeNavigation:
  Exclude:
    - 'db/migrate/20080828192131_add_family_to_martial_art.rb'

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, EnforcedStyleForEmptyBraces, SpaceBeforeBlockParameters.
# SupportedStyles: space, no_space
Style/SpaceInsideBlockBraces:
  Exclude:
    - 'app/models/attendance.rb'
    - 'test/test_helper.rb'

# Offense count: 1
# Cop supports --auto-correct.
Style/TrailingWhitespace:
  Exclude:
    - 'app/models/attendance.rb'
