# Offense count: 202
Metrics/AbcSize:
  Max: 228

# Offense count: 20
# Configuration parameters: CountComments.
Metrics/ClassLength:
  Max: 403

# Offense count: 35
Metrics/CyclomaticComplexity:
  Max: 27

# Offense count: 799
# Configuration parameters: AllowHeredoc, AllowURI, URISchemes.
# URISchemes: http, https
Metrics/LineLength:
  Max: 110

# Offense count: 179
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 161

# Offense count: 32
Metrics/PerceivedComplexity:
  Max: 27

# Offense count: 295
Style/Documentation:
  Enabled: false
