inherit_from: .rubocop_todo.yml
require:
  - rubocop-md
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  NewCops: enable
  Exclude:
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation
  IndentationWidth: 4

Layout/AssignmentIndentation:
  IndentationWidth: 4

Layout/FirstArgumentIndentation:
  EnforcedStyle: consistent
  IndentationWidth: 4

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/HashAlignment:
  EnforcedLastArgumentHashStyle: ignore_implicit

Layout/LineLength:
  Max: 107
  AllowHeredoc: true
  AllowURI: true
  IgnoreCopDirectives: true
  Exclude:
    - db/schema.rb

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
  IndentationWidth: 4

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented
  IndentationWidth: 4

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation
  IndentationWidth: 4

Metrics/BlockLength:
  Exclude:
    - config/environments/development.rb
    - config/environments/production.rb
    - config/routes.rb
    - db/schema.rb

Naming/MemoizedInstanceVariableName:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Rails:
  Enabled: true

Rails/FilePath:
  Enabled: false

Rails/UnknownEnv:
  Environments: development, test, beta, production

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/FormatString:
  EnforcedStyle: percent

Style/Lambda:
  EnforcedStyle: literal

Style/NumericLiterals:
  Exclude:
    - db/schema.rb

Style/NumericPredicate:
  Enabled: false

Style/RescueStandardError:
  EnforcedStyle: implicit

Style/SafeNavigation:
  ConvertCodeThatCanStartToReturnNil: true

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
