inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.3
  DisplayCopNames: true
  DisplayStyleGuide: true
  Include:
    - Capfile
    - Gemfile
    - Rakefile
    - config.ru
    - '*.gemspec'
    - '**/*.rake'
  Exclude:
    - 'tmp/**/*'

Layout/AlignHash:
  EnforcedLastArgumentHashStyle: ignore_implicit

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation
  IndentationWidth: 4

Layout/FirstParameterIndentation:
  EnforcedStyle: consistent
  IndentationWidth: 4

Layout/IndentArray:
  EnforcedStyle: consistent

Layout/IndentHash:
  EnforcedStyle: consistent

Layout/IndentAssignment:
  IndentationWidth: 4

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
  IndentationWidth: 4

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented
  IndentationWidth: 4

Metrics/BlockLength:
  Exclude:
    - config/environments/development.rb
    - config/environments/production.rb
    - config/routes.rb
    - db/schema.rb

Metrics/LineLength:
  Max: 100
  AllowHeredoc: true
  AllowURI: true
  IgnoreCopDirectives: true
  Exclude:
    - db/schema.rb

Naming/VariableNumber:
  Enabled: false

Rails:
  Enabled: true

Rails/FilePath:
  Enabled: false

Rails/UnknownEnv:
  Environments: development, test, beta, production

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/Encoding:
  Enabled: true

Style/FormatString:
  EnforcedStyle: percent

Style/Lambda:
  EnforcedStyle: literal

Style/NumericLiterals:
  Exclude:
    - db/schema.rb

Style/NumericPredicate:
  Enabled: false

Style/SafeNavigation:
  ConvertCodeThatCanStartToReturnNil: true

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma
