inherit_from: .rubocop_todo.yml
require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'

# FIXME(uwe): Remove when rubocop 1.0 is released
Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true
Layout/SpaceAroundMethodCallOperator:
  Enabled: true
Lint/DeprecatedOpenSSLConstant:
  Enabled: true
Lint/MixedRegexpCaptureTypes:
  Enabled: false
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Style/ExponentialNotation:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Style/RedundantRegexpCharacterClass:
  Enabled: true
Style/RedundantRegexpEscape:
  Enabled: true
Style/SlicingWithRange:
  Enabled: true
Style/RedundantFetchBlock:
  Enabled: true
Style/AccessorGrouping:
  Enabled: true
Style/BisectedAttrAccessor:
  Enabled: true
Style/RedundantAssignment:
  Enabled: true
Performance/AncestorsInclude:
  Enabled: true
Performance/BigDecimalWithNumericArgument:
  Enabled: true
Performance/RedundantSortBlock:
  Enabled: true
Performance/RedundantStringChars:
  Enabled: true
Performance/ReverseFirst:
  Enabled: true
Performance/SortReverse:
  Enabled: true
Performance/Squeeze:
  Enabled: true
Performance/StringInclude:
  Enabled: true
Lint/DuplicateElsifCondition:
  Enabled: true
Style/ArrayCoercion:
  Enabled: true
Style/CaseLikeIf:
  Enabled: true
Style/HashAsLastArrayItem:
  Enabled: true
Style/HashLikeCase:
  Enabled: true
Style/RedundantFileExtensionInRequire:
  Enabled: true
Rails/ActiveRecordCallbacksOrder:
  Enabled: true
Rails/FindById:
  Enabled: true
Rails/Inquiry:
  Enabled: true
Rails/MailerName:
  Enabled: true
Rails/MatchRoute:
  Enabled: true
Rails/NegateInclude:
  Enabled: true
Rails/Pluck:
  Enabled: true
Rails/PluckInWhere:
  Enabled: true
Rails/RenderInline:
  Enabled: true
Rails/RenderPlainText:
  Enabled: true
Rails/ShortI18n:
  Enabled: true
Rails/WhereExists:
  Enabled: true
Lint/BinaryOperatorWithIdenticalOperands:
  Enabled: true
Lint/DuplicateRescueException:
  Enabled: true
Lint/EmptyConditionalBody:
  Enabled: true
Lint/FloatComparison:
  Enabled: true
Lint/MissingSuper:
  Enabled: true
Lint/OutOfRangeRegexpRef:
  Enabled: true
Lint/SelfAssignment:
  Enabled: true
Lint/TopLevelReturnWithArgument:
  Enabled: true
Lint/UnreachableLoop:
  Enabled: true
Style/ExplicitBlockArgument:
  Enabled: true
Style/GlobalStdStream:
  Enabled: true
Style/OptionalBooleanParameter:
  Enabled: true
Style/SingleArgumentDig:
  Enabled: true
Style/StringConcatenation:
  Enabled: true
# EMXIF

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation
  IndentationWidth: 4

Layout/AssignmentIndentation:
  IndentationWidth: 4

Layout/FirstArgumentIndentation:
  EnforcedStyle: consistent
  IndentationWidth: 4

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/HashAlignment:
  EnforcedLastArgumentHashStyle: ignore_implicit

Layout/LineLength:
  Max: 107
  AllowHeredoc: true
  AllowURI: true
  IgnoreCopDirectives: true
  Exclude:
    - db/schema.rb

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
  IndentationWidth: 4

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented
  IndentationWidth: 4

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation
  IndentationWidth: 4

Metrics/BlockLength:
  Exclude:
    - config/environments/development.rb
    - config/environments/production.rb
    - config/routes.rb
    - db/schema.rb

Naming/MemoizedInstanceVariableName:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Rails:
  Enabled: true

Rails/FilePath:
  Enabled: false

Rails/UnknownEnv:
  Environments: development, test, beta, production

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/Encoding:
  Enabled: true

Style/FormatString:
  EnforcedStyle: percent

Style/Lambda:
  EnforcedStyle: literal

Style/NumericLiterals:
  Exclude:
    - db/schema.rb

Style/NumericPredicate:
  Enabled: false

Style/RescueStandardError:
  EnforcedStyle: implicit

Style/SafeNavigation:
  ConvertCodeThatCanStartToReturnNil: true

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
