inherit_from: .rubocop_todo.yml
require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - 'tmp/**/*'
    - 'vendor/**/*'

Layout/AlignHash:
  EnforcedLastArgumentHashStyle: ignore_implicit

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, IndentationWidth.
# SupportedStyles: with_first_argument, with_fixed_indentation
Layout/AlignArguments:
  EnforcedStyle: with_fixed_indentation
  IndentationWidth: 4

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation
  IndentationWidth: 4

Layout/IndentFirstArgument:
  EnforcedStyle: consistent
  IndentationWidth: 4

Layout/IndentFirstArrayElement:
  EnforcedStyle: consistent

Layout/IndentFirstHashElement:
  EnforcedStyle: consistent

Layout/IndentAssignment:
  IndentationWidth: 4

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
  IndentationWidth: 4

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented
  IndentationWidth: 4

Metrics/BlockLength:
  Exclude:
    - config/environments/development.rb
    - config/environments/production.rb
    - config/routes.rb
    - db/schema.rb

Metrics/LineLength:
  Max: 108
  AllowHeredoc: true
  AllowURI: true
  IgnoreCopDirectives: true
  Exclude:
    - db/schema.rb

Naming/MemoizedInstanceVariableName:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Rails:
  Enabled: true

Rails/FilePath:
  Enabled: false

Rails/UnknownEnv:
  Environments: development, test, beta, production

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/Encoding:
  Enabled: true

Style/FormatString:
  EnforcedStyle: percent

Style/Lambda:
  EnforcedStyle: literal

Style/NumericLiterals:
  Exclude:
    - db/schema.rb

Style/NumericPredicate:
  Enabled: false

Style/RescueStandardError:
  EnforcedStyle: implicit

Style/SafeNavigation:
  ConvertCodeThatCanStartToReturnNil: true

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
