# Offense count: 201
Metrics/AbcSize:
  Max: 228

# Offense count: 19
# Configuration parameters: CountComments.
Metrics/ClassLength:
  Max: 384

# Offense count: 35
Metrics/CyclomaticComplexity:
  Max: 27

# Offense count: 953
# Configuration parameters: AllowHeredoc, AllowURI, URISchemes.
# URISchemes: http, https
Metrics/LineLength:
  Max: 170

# Offense count: 161
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 155

# Offense count: 31
Metrics/PerceivedComplexity:
  Max: 27

# Offense count: 294
Style/Documentation:
  Enabled: false
