# Offense count: 202
Metrics/AbcSize:
  Max: 228

# Offense count: 20
# Configuration parameters: CountComments.
Metrics/ClassLength:
  Max: 393

# Offense count: 35
Metrics/CyclomaticComplexity:
  Max: 27

# Offense count: 877
# Configuration parameters: AllowHeredoc, AllowURI, URISchemes.
# URISchemes: http, https
Metrics/LineLength:
  Max: 130

# Offense count: 166
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 157

# Offense count: 32
Metrics/PerceivedComplexity:
  Max: 27

# Offense count: 294
Style/Documentation:
  Enabled: false
