# Offense count: 202
Metrics/AbcSize:
  Max: 228

# Offense count: 20
# Configuration parameters: CountComments.
Metrics/ClassLength:
  Max: 409

# Offense count: 35
Metrics/CyclomaticComplexity:
  Max: 27

# Offense count: 205
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 169

# Offense count: 32
Metrics/PerceivedComplexity:
  Max: 27

# Offense count: 76
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: strict, flexible
Rails/Date:
  Enabled: false

# Offense count: 10
# Cop supports --auto-correct.
# Configuration parameters: Include.
# Include: app/models/**/*.rb
Rails/FindBy:
  Exclude:
    - 'app/models/member.rb'
    - 'app/models/news_publisher.rb'
    - 'app/models/nkf_appointments_scraper.rb'
    - 'app/models/nkf_member_import.rb'
    - 'app/models/role.rb'
    - 'app/models/semester.rb'
    - 'app/models/user.rb'

# Offense count: 3
# Configuration parameters: Include.
# Include: app/models/**/*.rb
Rails/HasAndBelongsToMany:
  Exclude:
    - 'app/models/event.rb'
    - 'app/models/group.rb'
    - 'app/models/member.rb'

# Offense count: 9
# Configuration parameters: Include.
# Include: app/**/*.rb, config/**/*.rb, db/**/*.rb, lib/**/*.rb
Rails/Output:
  Exclude:
    - 'db/migrate/20080828193209_add_martial_arts_members.rb'
    - 'db/migrate/20080828214833_fix_future_birthdates.rb'
    - 'db/migrate/20080828220940_create_groups.rb'
    - 'db/migrate/20120604144204_create_member_images.rb'
    - 'db/migrate/20150617115412_add_decoration_to_ranks.rb'

# Offense count: 4
Rails/OutputSafety:
  Exclude:
    - 'app/helpers/application_helper.rb'
    - 'app/helpers/user_helper.rb'
    - 'app/mailers/user_message_mailer.rb'
    - 'app/models/event_invitee_message.rb'

# Offense count: 51
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: strict, flexible
Rails/TimeZone:
  Enabled: false

# Offense count: 295
Style/Documentation:
  Enabled: false
