#!/bin/bash
#
# rjjk_web      Startup script for the RJJK web application
#
# chkconfig: 345 88 12
# description: RJJK web application
# pidfile: /u/apps/$app/shared/log/mongrel.pid

. /etc/rc.d/init.d/functions

APP=rjjk_web
RUN_AS_USER=capistrano
PORT=3005
APP_DIR=/u/apps/$APP/current
pidfile=${PIDFILE-/u/apps/$APP/shared/log/mongrel.pid}

START_CMD="mongrel_rails start -p $PORT -e production -c $APP_DIR -d 1>/u/apps/$APP/shared/log/stdout.log 2>/u/apps/$APP/shared/log/stderr.log"
STOP_CMD="mongrel_rails stop -c $APP_DIR"
START_FERRET_CMD="cd $APP_DIR ; RAILS_ENV=production ruby script/ferret_start"
STOP_FERRET_CMD="cd $APP_DIR ; RAILS_ENV=production ruby script/ferret_stop"
RESTART_CMD="mongrel_rails restart -c $APP_DIR"

USER=`whoami`

run() {
	cmd=$1
	if [ "$USER" != "$RUN_AS_USER" ]; then
		echo Running as $USER
        echo su - $RUN_AS_USER -c "$cmd"
        su - $RUN_AS_USER -c "$cmd"
    else
    	echo $cmd
        $cmd
    fi
}

# See how we were called.
case "$1" in
  start)
    run "$START_FERRET_CMD"
    run "$START_CMD"
        ;;
  stop)
    run "$STOP_FERRET_CMD"
    run "$STOP_CMD"
    rm -f ${pidfile}
        ;;
  restart)
    run "$STOP_FERRET_CMD"
    run "$START_FERRET_CMD"
    run "$RESTART_CMD"
        ;;
  status)
        ps -ef | grep $app
        ;;
  *)
        echo $"Usage: $prog {start|stop|restart|status}"
        exit 1
esac

exit 0
