#!/bin/bash
#
# rjjk_web      Startup script for the RJJK web application
#
# chkconfig: 345 88 12
# description: RJJK web application

# See how we were called.
case "$1" in
  start)
        su - capistrano -c "cd /u/apps/rjjk_web/current;RAILS_ENV=production ruby script/ferret_start"
        su - capistrano -c "mongrel_rails start -p 3005 -e production -c /u/apps/rjjk_web/current -d 1>/u/apps/rjjk_web/shared/log/stdout.log 2>/u/apps/rjjk_web/shared/log/stderr.log"
        ;;
  stop)
        su - capistrano -c "mongrel_rails stop -c /u/apps/rjjk_web/current"
        su - capistrano -c "cd /u/apps/rjjk_web/current;RAILS_ENV=production ruby script/ferret_stop"
        ;;
  restart)
        su - capistrano -c "cd /u/apps/rjjk_web/current;RAILS_ENV=production ruby script/ferret_stop"
        su - capistrano -c "cd /u/apps/rjjk_web/current;RAILS_ENV=production ruby script/ferret_start"
        su - capistrano -c "mongrel_rails restart -c /u/apps/rjjk_web/current"
        ;;
  status)
        ps -ef | grep rjjk_web
        ;;
  *)
        echo $"Usage: $prog {start|stop|restart|status}"
        exit 1
esac

exit 0
