#!/bin/bash
#
# rjjk_nagger      Startup script for the RJJK Nagger
#
# chkconfig: 345 88 12
# description: RJJK Nagger
# pidfile: /u/apps/$APP/shared/log/nagger.pid

. /etc/rc.d/init.d/functions

APP=rjjk_web
RUN_AS_USER=capistrano

pidfile=${PIDFILE-/u/apps/$APP/shared/log/nagger.pid}
APP_DIR="/u/apps/$APP/current"
LOG_DIR="/u/apps/$APP/shared/log"

JRUBY_OPTS="--server"
CMD_ENV="export JAVA_HOME=/usr/java/default ; export JRUBY_HOME=/usr/local/jruby ; export PATH=\$JAVA_HOME/bin:\$JRUBY_HOME/bin:\$PATH ; jruby --version ; jruby -J-Xmx2G --server -S bundle exec trinidad -p $PORT -e production -t -ldaemon --daemonize $pidfile $APP_DIR 1>$LOG_DIR/stdout.log 2>$LOG_DIR/stderr.log"
START_CMD="cd $APP_DIR ; $CMD_ENV ; jruby --version ; jruby $JRUBY_OPTS -S rails runner -e production Nagger.start 1>$LOG_DIR/nagger_stdout.log 2>$LOG_DIR/nagger_stderr.log"
STOP_CMD="kill `cat $pidfile`"

USER=`whoami`

run() {
	cmd=$1
	if [ "$USER" != "$RUN_AS_USER" ]; then
		echo Running as $USER
        echo su - $RUN_AS_USER -c \"$cmd\"
        su - $RUN_AS_USER -c "$cmd"
    else
    	echo $cmd
        eval $cmd
    fi
}

# See how we were called.
case "$1" in
  start)
	if [ -f $pidfile ] && ! ps h `cat $pidfile` > /dev/null
	then
	    rm -f $pidfile
	fi
#    run "$START_FERRET_CMD"
    run "$START_CMD"
        ;;
  stop)
#    run "$STOP_FERRET_CMD"
    run "$STOP_CMD"
    rm -f ${pidfile}
        ;;
  restart)
#    run "$STOP_FERRET_CMD"
#    run "$START_FERRET_CMD"
    run "$STOP_CMD"
    rm -f ${pidfile}
    run "$START_CMD"
        ;;
  status)
        ps -ef | grep $APP
        ;;
  *)
        echo "Usage: $prog {start|stop|restart|status}"
        exit 1
esac

exit 0
