#!/bin/bash
#
# rjjk_web      Startup script for the RJJK web application
#
# chkconfig: 345 88 12
# description: RJJK web application
# pidfile: /u/apps/$APP/shared/log/server.pid

. /etc/rc.d/init.d/functions

APP=rjjk_web
RAILS_ENV=production
PORT=3005
RUN_AS_USER=capistrano
pidfile=${PIDFILE-/u/apps/$APP/shared/pids/server.pid}
APP_DIR="/u/apps/$APP/current"
LOG_DIR="/u/apps/$APP/shared/log"

START_CMD="cd $APP_DIR ;
  export JAVA_HOME=/usr/java/default ;
  export JRUBY_HOME=/usr/local/jruby ;
  export PATH=\$JRUBY_HOME/bin:\$JAVA_HOME/bin:\$PATH ;
  export JRUBY_OPTS='--2.0 -J-Xmx2G --server -J-Djava.awt.headless=true -J-Dawt.toolkit=sun.awt.HToolkit' ;
  jruby --version ;
  (jruby -S bundle exec torqbox -p $PORT -E $RAILS_ENV 1>$LOG_DIR/stdout.log 2>$LOG_DIR/stderr.log) &
  PID=\$! ;
  echo \$PID > $pidfile ;
  echo PID: \$PID
"

USER=`whoami`

run() {
	cmd=$1
	if [ "$USER" != "$RUN_AS_USER" ]; then
		echo Running as $USER
        echo su - $RUN_AS_USER -c \"$cmd\"
        su - $RUN_AS_USER -c "$cmd"
    else
    	echo $cmd
        eval $cmd
    fi
}

start() {
  if [ -f $pidfile ] ; then
    PID=`cat $pidfile`
    if [ `ps h $PID > /dev/null` ] ; then
      echo $APP is already running.
      exit 1
    fi
  fi
  run "$START_CMD"
}

stop() {
  if [ -f $pidfile ] ; then
    PID=`cat $pidfile`
    if ps h $PID > /dev/null ; then
      run "kill $PID"
    else
      echo deleting stale PID file $PID
    fi
    rm -f ${pidfile}
  else
    echo $APP is not running.
  fi
}

# See how we were called.
case "$1" in
  start)
    start
        ;;
  stop)
    stop
        ;;
  restart)
    stop
    start
        ;;
  status)
    if [ -f $pidfile ] ; then
      PID=`cat $pidfile`
      if kill -0 $PID ; then
        echo $APP is running as $PID
      else
        echo $APP pid $PID is dead!
      fi
    else
      echo $APP is not running.
    fi
        ;;
  *)
        echo "Usage: $prog {start|stop|restart|status}"
        exit 1
esac

exit 0
