# frozen_string_literal: true

require 'test_helper'

class NkfMemberSyncJobTest < ActiveJob::TestCase
  include ActionMailer::TestHelper

  test 'sync' do
    VCR.use_cassette('NkfMemberSyncJob_lars', match_requests_on: %i[method host path query]) do
      assert_emails(12) { NkfMemberSyncJob.perform_now(members(:lars)) }
      assert_equal <<~SUBJECTS.chomp, ActionMailer::Base.deliveries.map(&:subject).join("\n")
        [RJJK][TEST]  (RuntimeError) "Failed to synchronize value with NKF member: id: 228855109, RJJK: user.first_name: \\"Lars\\...
        [RJJK][TEST]  (RuntimeError) "Failed to synchronize value with NKF member: id: 228855109, RJJK: user.address: \\"Torsvei ...
        [RJJK][TEST]  (RuntimeError) "Failed to synchronize value with NKF member: id: 228855109, RJJK: user.birthdate: \\"21.06....
        [RJJK][TEST]  (RuntimeError) "Failed to synchronize value with NKF member: id: 228855109, RJJK: membership.phone_home: \\...
        [RJJK][TEST]  (RuntimeError) "Failed to synchronize value with NKF member: id: 228855109, RJJK: membership.phone_work: \\...
        [RJJK][TEST]  (RuntimeError) "Failed to synchronize value with NKF member: id: 228855109, RJJK: user.phone: \\"\\", NKF: m...
        [RJJK][TEST]  (RuntimeError) "Failed to synchronize value with NKF member: id: 228855109, RJJK: user.contact_email: \\"la...
        [RJJK][TEST]  (RuntimeError) "Failed to synchronize value with NKF member: id: 228855109, RJJK: membership.category: \\"V...
        [RJJK][TEST]  (RuntimeError) "Failed to synchronize value with NKF member: id: 228855109, RJJK: membership.category: \\"V...
        [RJJK][TEST]  (RuntimeError) "Failed to synchronize value with NKF member: id: 228855109, RJJK: membership.contract: \\"V...
        [RJJK][TEST]  (RuntimeError) "Failed to synchronize value with NKF member: id: 228855109, RJJK: membership.discount: \\"1...
        [RJJK][TEST]  (RuntimeError) "Failed to synchronize value with NKF member: id: 228855109, RJJK: membership.joined_on: \\"...
      SUBJECTS
    end
  end
end
